name: main
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.362+9
          distribution: adopt

      - name: Set the build version
        run: |
          set -eu
          echo "export BUILD_VERSION=$( make dev/version )" | tee -a $GITHUB_ENV

      - name: Install and run tests
        run: mvn clean -B install

      - name: Set up JDK 1.8 with Maven Central
        uses: actions/setup-java@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        with:
          java-version: 8.0.362+9
          distribution: adopt
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Stage package
        if: github.ref == 'refs/heads/develop'
        run: make deploy/staging
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Publish package
        if: github.ref == 'refs/heads/main'
        run: make deploy/prod
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
